import { CompetitorConfig } from "./types";

export const competitors: CompetitorConfig[] = [
  {
    id: "pinkblue",
    name: "Pinkblue",
    color: "#ec4899",
    bgLight: "#fce7f3",
    baseUrl: "https://www.pinkblue.in",
    domain: "pinkblue.in",
  },
  {
    id: "medikabazar",
    name: "Medikabazar",
    color: "#f97316",
    bgLight: "#ffedd5",
    baseUrl: "https://www.medikabazaar.com",
    domain: "medikabazaar.com",
  },
  {
    id: "oralkart",
    name: "Oralkart",
    color: "#8b5cf6",
    bgLight: "#ede9fe",
    baseUrl: "https://www.oralkart.com",
    domain: "oralkart.com",
  },
  {
    id: "dentmark",
    name: "Dentmark",
    color: "#ea580c",
    bgLight: "#fff7ed",
    baseUrl: "https://www.dentmark.com",
    domain: "dentmark.com",
  },
  {
    id: "metroorthodontics",
    name: "Metro Ortho",
    color: "#0ea5e9",
    bgLight: "#e0f2fe",
    baseUrl: "https://www.metroorthodontics.in",
    domain: "metroorthodontics.in",
  },
  {
    id: "shop4smile",
    name: "Shop4Smile",
    color: "#14b8a6",
    bgLight: "#ccfbf1",
    baseUrl: "https://shop4smile.in",
    domain: "shop4smile.in",
  },
  {
    id: "surgicalmart",
    name: "SurgicalMart",
    color: "#6366f1",
    bgLight: "#e0e7ff",
    baseUrl: "https://surgicalmart.com",
    domain: "surgicalmart.com",
  },
  {
    id: "smilestream",
    name: "SmileStream",
    color: "#d946ef",
    bgLight: "#fae8ff",
    baseUrl: "https://smilestreamsolutions.com",
    domain: "smilestreamsolutions.com",
  },
  {
    id: "dentaid",
    name: "Dentaid",
    color: "#f59e0b",
    bgLight: "#fef3c7",
    baseUrl: "https://dentaiddevices.com",
    domain: "dentaiddevices.com",
  },
];

export const dentalkartConfig = {
  id: "dentalkart",
  name: "Dentalkart",
  color: "#3b82f6",
  bgLight: "#dbeafe",
  baseUrl: "https://www.dentalkart.com",
  domain: "dentalkart.com",
};
